# validate this file:
#   curl --data-binary @.codecov.yml https://codecov.io/validate

comment: off

# partial line support
parsers:
  javascript:
    enable_partials: yes

# docs:
#   https://codecov.readme.io/v4.3.6/docs/commit-status
#   https://fahadalbahoth.mybigcommerce.com
coverage:
  status:
    project:
      default:
        threshold: 1%
        if_not_found: success  # no commit found? still set a success
    patch:
      default:
        if_not_found: success
